package com.seismic.crm.model;

// Generated Jan 13, 2014 1:38:11 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * ChecklistResponse generated by hbm2java
 */
@Entity
@Table(name = "ChecklistResponse", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class ChecklistResponse implements java.io.Serializable {

	private long checklistResponseId;
	private SalesOrder salesOrder;
	private ChecklistDocument checklistDocument;
	private ChecklistProductCategory checklistProductCategory;
	private String checklistFileKey;
	private String checklistFilename;
	private Boolean checklistResponseStatus = false;
	private Long checklistResponseUserId;
	private Date checklistResponseDate;
	private Boolean isActive;
	private String createdby;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;

	public ChecklistResponse() {
	}

	public ChecklistResponse(long checklistResponseId) {
		this.checklistResponseId = checklistResponseId;
	}

	public ChecklistResponse(long checklistResponseId, SalesOrder salesOrder,
			ChecklistDocument checklistDocument,
			ChecklistProductCategory checklistProductCategory,
			Boolean checklistResponseStatus, Long checklistResponseUserId,
			Date checklistResponseDate, Boolean isActive, String createdby,
			Date createdAt, String modifiedBy, Date modifiedAt, String remarks) {
		this.checklistResponseId = checklistResponseId;
		this.salesOrder = salesOrder;
		this.checklistDocument = checklistDocument;
		this.checklistProductCategory = checklistProductCategory;
		this.checklistResponseStatus = checklistResponseStatus;
		this.checklistResponseUserId = checklistResponseUserId;
		this.checklistResponseDate = checklistResponseDate;
		this.isActive = isActive;
		this.createdby = createdby;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue
	@Column(name = "ChecklistResponseID", unique = true, nullable = false)
	public long getChecklistResponseId() {
		return this.checklistResponseId;
	}

	public void setChecklistResponseId(long checklistResponseId) {
		this.checklistResponseId = checklistResponseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChecklistResponseSalesOrderID")
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChecklistResponseDocumentID")
	public ChecklistDocument getChecklistDocument() {
		return this.checklistDocument;
	}

	public void setChecklistDocument(ChecklistDocument checklistDocument) {
		this.checklistDocument = checklistDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChecklistResponseProductCategoryID")
	public ChecklistProductCategory getChecklistProductCategory() {
		return this.checklistProductCategory;
	}

	public void setChecklistProductCategory(
			ChecklistProductCategory checklistProductCategory) {
		this.checklistProductCategory = checklistProductCategory;
	}

	@Column(name = "ChecklistResponseStatus")
	public Boolean getChecklistResponseStatus() {
		return this.checklistResponseStatus;
	}

	public void setChecklistResponseStatus(Boolean checklistResponseStatus) {
		this.checklistResponseStatus = checklistResponseStatus;
	}

	@Column(name = "ChecklistResponseUserID")
	public Long getChecklistResponseUserId() {
		return this.checklistResponseUserId;
	}

	public void setChecklistResponseUserId(Long checklistResponseUserId) {
		this.checklistResponseUserId = checklistResponseUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ChecklistResponseDate", length = 23)
	public Date getChecklistResponseDate() {
		return this.checklistResponseDate;
	}

	public void setChecklistResponseDate(Date checklistResponseDate) {
		this.checklistResponseDate = checklistResponseDate;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Createdby")
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "ChecklistFileKey")
	public String getChecklistFileKey() {
		return checklistFileKey;
	}

	public void setChecklistFileKey(String checklistFileKey) {
		this.checklistFileKey = checklistFileKey;
	}

	@Column(name = "ChecklistFilename")
	public String getChecklistFilename() {
		return checklistFilename;
	}

	public void setChecklistFilename(String checklistFilename) {
		this.checklistFilename = checklistFilename;
	}

}
