package com.seismic.crm.model;

// Generated Dec 21, 2013 5:30:19 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * GeneralActivityTasks generated by hbm2java
 */
@Entity
@Table(name = "GeneralActivityTasks", schema = "dbo", catalog = "Seismic_Crm_Dev")
public class GeneralActivityTasks implements java.io.Serializable {

	private long generalActivityTaskId;
	private GeneralActivities generalActivities;
	private String generalActivityTaskAction;
	private String generalActivityTaskStatus;
	private String generalActivityNotes;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;

	public GeneralActivityTasks() {
	}

	public GeneralActivityTasks(long generalActivityTaskId) {
		this.generalActivityTaskId = generalActivityTaskId;
	}

	public GeneralActivityTasks(long generalActivityTaskId,
			GeneralActivities generalActivities,
			String generalActivityTaskAction, String generalActivityTaskStatus,
			String generalActivityNotes, Boolean isActive, String createdBy,
			Date createdAt, String modifiedBy, Date modifiedAt, String remarks) {
		this.generalActivityTaskId = generalActivityTaskId;
		this.generalActivities = generalActivities;
		this.generalActivityTaskAction = generalActivityTaskAction;
		this.generalActivityTaskStatus = generalActivityTaskStatus;
		this.generalActivityNotes = generalActivityNotes;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "GeneralActivityTaskID", unique = true, nullable = false)
	public long getGeneralActivityTaskId() {
		return this.generalActivityTaskId;
	}

	public void setGeneralActivityTaskId(long generalActivityTaskId) {
		this.generalActivityTaskId = generalActivityTaskId;
	}
	@JsonManagedReference
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "GeneralActivityID")
	public GeneralActivities getGeneralActivities() {
		return this.generalActivities;
	}

	public void setGeneralActivities(GeneralActivities generalActivities) {
		this.generalActivities = generalActivities;
	}

	@Column(name = "GeneralActivityTaskAction")
	public String getGeneralActivityTaskAction() {
		return this.generalActivityTaskAction;
	}

	public void setGeneralActivityTaskAction(String generalActivityTaskAction) {
		this.generalActivityTaskAction = generalActivityTaskAction;
	}

	@Column(name = "GeneralActivityTaskStatus")
	public String getGeneralActivityTaskStatus() {
		return this.generalActivityTaskStatus;
	}

	public void setGeneralActivityTaskStatus(String generalActivityTaskStatus) {
		this.generalActivityTaskStatus = generalActivityTaskStatus;
	}

	@Column(name = "GeneralActivityNotes")
	public String getGeneralActivityNotes() {
		return this.generalActivityNotes;
	}

	public void setGeneralActivityNotes(String generalActivityNotes) {
		this.generalActivityNotes = generalActivityNotes;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
