package com.seismic.crm.model;

// Generated Aug 30, 2013 5:59:17 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ListValues generated by hbm2java
 */
@Entity
@Table(name = "ListValues", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class ListValues implements java.io.Serializable {

	private long listValueId;
	private String listValueCategory;
	private String listValueSubCategory;
	private Integer listValue;
	private String listValueDescription;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private String modifiedAt;
	private String remarks;
//	private Set contactGroups = new HashSet(0);
//	private Set contractProductDetails = new HashSet(0);
//	private Set contracts = new HashSet(0);
//	private Set contacts = new HashSet(0);
//	private Set accounts = new HashSet(0);
//	private Set inventorySerializedProducts = new HashSet(0);
//	private Set addresses = new HashSet(0);
//	private Set contactGroupMembers = new HashSet(0);
//	private Set serviceRequests = new HashSet(0);

	public ListValues() {
	}

	public ListValues(long listValueId) {
		this.listValueId = listValueId;
	}

	public ListValues(long listValueId, String listValueCategory,
			String listValueSubCategory, Integer listValue,
			String listValueDescription, Boolean isActive, String createdBy,
			Date createdAt, String modifiedBy, String modifiedAt,
			String remarks/*, Set contactGroups, Set contractProductDetails,
			Set contracts, Set contacts, Set accounts,
			Set inventorySerializedProducts, Set addresses,
			Set contactGroupMembers, Set serviceRequests*/) {
		this.listValueId = listValueId;
		this.listValueCategory = listValueCategory;
		this.listValueSubCategory = listValueSubCategory;
		this.listValue = listValue;
		this.listValueDescription = listValueDescription;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
//		this.contactGroups = contactGroups;
//		this.contractProductDetails = contractProductDetails;
//		this.contracts = contracts;
//		this.contacts = contacts;
//		this.accounts = accounts;
//		this.inventorySerializedProducts = inventorySerializedProducts;
//		this.addresses = addresses;
//		this.contactGroupMembers = contactGroupMembers;
//		this.serviceRequests = serviceRequests;
	}

	@Id
	@Column(name = "ListValueID", unique = true, nullable = false)
	public long getListValueId() {
		return this.listValueId;
	}

	public void setListValueId(long listValueId) {
		this.listValueId = listValueId;
	}

	@Column(name = "ListValueCategory")
	public String getListValueCategory() {
		return this.listValueCategory;
	}

	public void setListValueCategory(String listValueCategory) {
		this.listValueCategory = listValueCategory;
	}

	@Column(name = "ListValue_SubCategory")
	public String getListValueSubCategory() {
		return this.listValueSubCategory;
	}

	public void setListValueSubCategory(String listValueSubCategory) {
		this.listValueSubCategory = listValueSubCategory;
	}

	@Column(name = "ListValue")
	public Integer getListValue() {
		return this.listValue;
	}

	public void setListValue(Integer listValue) {
		this.listValue = listValue;
	}

	@Column(name = "ListValueDescription")
	public String getListValueDescription() {
		return this.listValueDescription;
	}

	public void setListValueDescription(String listValueDescription) {
		this.listValueDescription = listValueDescription;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ModifiedAt")
	public String getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(String modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getContactGroups() {
//		return this.contactGroups;
//	}
//
//	public void setContactGroups(Set contactGroups) {
//		this.contactGroups = contactGroups;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getContractProductDetails() {
//		return this.contractProductDetails;
//	}
//
//	public void setContractProductDetails(Set contractProductDetails) {
//		this.contractProductDetails = contractProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getContracts() {
//		return this.contracts;
//	}
//
//	public void setContracts(Set contracts) {
//		this.contracts = contracts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getContacts() {
//		return this.contacts;
//	}
//
//	public void setContacts(Set contacts) {
//		this.contacts = contacts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getAccounts() {
//		return this.accounts;
//	}
//
//	public void setAccounts(Set accounts) {
//		this.accounts = accounts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getInventorySerializedProducts() {
//		return this.inventorySerializedProducts;
//	}
//
//	public void setInventorySerializedProducts(Set inventorySerializedProducts) {
//		this.inventorySerializedProducts = inventorySerializedProducts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getAddresses() {
//		return this.addresses;
//	}
//
//	public void setAddresses(Set addresses) {
//		this.addresses = addresses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getContactGroupMembers() {
//		return this.contactGroupMembers;
//	}
//
//	public void setContactGroupMembers(Set contactGroupMembers) {
//		this.contactGroupMembers = contactGroupMembers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listValues")
//	public Set getServiceRequests() {
//		return this.serviceRequests;
//	}
//
//	public void setServiceRequests(Set serviceRequests) {
//		this.serviceRequests = serviceRequests;
//	}

}
