package com.seismic.crm.model;

// Generated 6 Jan, 2014 3:41:50 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OpportunityProductDetail generated by hbm2java
 */
@Entity
@Table(name = "OpportunityProductDetail", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class OpportunityProductDetail implements java.io.Serializable {

	private String opportunityProdDetailId;
	private Opportunity opportunity;
	private Product product;
	private String opportunityName;
//	private String unitofMeasure;
	private Boolean serialized;
	private String opportunityProductQty;
	private String opportunityProductRate;
	private String opportunityProductDiscount;
	private BigDecimal opportunityProductTotal;
	private BigDecimal opportunityProductCurrency;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private String modifiedAt;
	private String remarks;

	public OpportunityProductDetail() {
	}

	public OpportunityProductDetail(String opportunityProdDetailId) {
		this.opportunityProdDetailId = opportunityProdDetailId;
	}

	public OpportunityProductDetail(String opportunityProdDetailId,
			Opportunity opportunity, Product product, String opportunityName,
			/*String unitofMeasure,*/ Boolean serialized, String opportunityProductQty,
			String opportunityProductRate, String opportunityProductDiscount,
			BigDecimal opportunityProductTotal,
			BigDecimal opportunityProductCurrency, Boolean isActive,
			String createdBy, Date createdAt, String modifiedBy,
			String modifiedAt, String remarks) {
		this.opportunityProdDetailId = opportunityProdDetailId;
		this.opportunity = opportunity;
		this.product = product;
		this.opportunityName = opportunityName;
//		this.unitofMeasure = unitofMeasure;
		this.serialized = serialized;
		this.opportunityProductQty = opportunityProductQty;
		this.opportunityProductRate = opportunityProductRate;
		this.opportunityProductDiscount = opportunityProductDiscount;
		this.opportunityProductTotal = opportunityProductTotal;
		this.opportunityProductCurrency = opportunityProductCurrency;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "OpportunityProdDetailID", unique = true, nullable = false)
	public String getOpportunityProdDetailId() {
		return this.opportunityProdDetailId;
	}

	public void setOpportunityProdDetailId(String opportunityProdDetailId) {
		this.opportunityProdDetailId = opportunityProdDetailId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OpportunityID")
	public Opportunity getOpportunity() {
		return this.opportunity;
	}

	public void setOpportunity(Opportunity opportunity) {
		this.opportunity = opportunity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OpportunityProductID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "OpportunityName")
	public String getOpportunityName() {
		return this.opportunityName;
	}

	public void setOpportunityName(String opportunityName) {
		this.opportunityName = opportunityName;
	}

	/*@Column(name = "UnitofMeasure")
	public String getUnitofMeasure() {
		return this.unitofMeasure;
	}

	public void setUnitofMeasure(String unitofMeasure) {
		this.unitofMeasure = unitofMeasure;
	}*/

	@Column(name = "Serialized")
	public Boolean getSerialized() {
		return this.serialized;
	}

	public void setSerialized(Boolean serialized) {
		this.serialized = serialized;
	}

	@Column(name = "OpportunityProductQty")
	public String getOpportunityProductQty() {
		return this.opportunityProductQty;
	}

	public void setOpportunityProductQty(String opportunityProductQty) {
		this.opportunityProductQty = opportunityProductQty;
	}

	@Column(name = "OpportunityProductRate")
	public String getOpportunityProductRate() {
		return this.opportunityProductRate;
	}

	public void setOpportunityProductRate(String opportunityProductRate) {
		this.opportunityProductRate = opportunityProductRate;
	}

	@Column(name = "OpportunityProductDiscount")
	public String getOpportunityProductDiscount() {
		return this.opportunityProductDiscount;
	}

	public void setOpportunityProductDiscount(String opportunityProductDiscount) {
		this.opportunityProductDiscount = opportunityProductDiscount;
	}

	@Column(name = "OpportunityProductTotal", precision = 20)
	public BigDecimal getOpportunityProductTotal() {
		return this.opportunityProductTotal;
	}

	public void setOpportunityProductTotal(BigDecimal opportunityProductTotal) {
		this.opportunityProductTotal = opportunityProductTotal;
	}

	@Column(name = "OpportunityProductCurrency", scale = 4)
	public BigDecimal getOpportunityProductCurrency() {
		return this.opportunityProductCurrency;
	}

	public void setOpportunityProductCurrency(
			BigDecimal opportunityProductCurrency) {
		this.opportunityProductCurrency = opportunityProductCurrency;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "ModifiedAt")
	public String getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(String modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
