package com.seismic.crm.model;

// Generated Nov 13, 2013 3:55:26 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class Product implements java.io.Serializable {

	private long productId;
	private ProductSubType productSubType;
	private ProductCategory productCategory;
	private ProductSubCategory productSubCategory;
	private ProductType productType;
	private SupplierProduct supplierProduct;
//	private ProductDiscount productDiscount;
	private String productName;
	private String productDescription;
	private String productNumber;
	private Date purchasedAt;
	private BigDecimal wholeSaleRate;
	private BigDecimal retailRate;
	private String productUom;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
//	private Set inventoryBookings = new HashSet(0);
//	private Set opportunityProductDetails = new HashSet(0);
//	private Set priceLevels = new HashSet(0);
//	private Set supplierProducts = new HashSet(0);
//	private Set productBundleDetails = new HashSet(0);
//	private Set inventoryProducts = new HashSet(0);
//	private Set projectActivityManagements = new HashSet(0);
//	private Set salesOrderProductDetails = new HashSet(0);
//	private Set projectTasks = new HashSet(0);
//	private Set priceLists = new HashSet(0);
//	private Set inventoryActualstockSerializedProducts = new HashSet(0);
//	private Set quoteProductDetails = new HashSet(0);
//	private Set inventoryIssues = new HashSet(0);
//	private Set salesOrderSpecResponses = new HashSet(0);
//	private Set inventoryActualStocks = new HashSet(0);
//	private Set contractProductDetails = new HashSet(0);
//	private Set assetMovements = new HashSet(0);
//	private Set salesOrderProductDetails_1 = new HashSet(0);

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

//	public Product(long productId, ProductSubType productSubType,
//			ProductCategory productCategory,
//			ProductSubCategory productSubCategory, ProductType productType,
//			SupplierProduct supplierProduct, ProductDiscount productDiscount,
//			String productName, String productDescription,
//			String productNumber, Date purchasedAt, BigDecimal wholeSaleRate,
//			BigDecimal retailRate, String productUom, Boolean isActive,
//			String createdBy, Date createdAt, String modifiedBy,
//			Date modifiedAt, String remarks, Set inventoryBookings,
//			Set opportunityProductDetails, Set priceLevels,
//			Set supplierProducts, Set productBundleDetails,
//			Set inventoryProducts, Set projectActivityManagements,
//			Set salesOrderProductDetails, Set projectTasks, Set priceLists,
//			Set inventoryActualstockSerializedProducts,
//			Set quoteProductDetails, Set inventoryIssues,
//			Set salesOrderSpecResponses, Set inventoryActualStocks,
//			Set contractProductDetails, Set assetMovements,
//			Set salesOrderProductDetails_1) {
//		this.productId = productId;
//		this.productSubType = productSubType;
//		this.productCategory = productCategory;
//		this.productSubCategory = productSubCategory;
//		this.productType = productType;
//		this.supplierProduct = supplierProduct;
//		this.productDiscount = productDiscount;
//		this.productName = productName;
//		this.productDescription = productDescription;
//		this.productNumber = productNumber;
//		this.purchasedAt = purchasedAt;
//		this.wholeSaleRate = wholeSaleRate;
//		this.retailRate = retailRate;
//		this.productUom = productUom;
//		this.isActive = isActive;
//		this.createdBy = createdBy;
//		this.createdAt = createdAt;
//		this.modifiedBy = modifiedBy;
//		this.modifiedAt = modifiedAt;
//		this.remarks = remarks;
//		this.inventoryBookings = inventoryBookings;
//		this.opportunityProductDetails = opportunityProductDetails;
//		this.priceLevels = priceLevels;
//		this.supplierProducts = supplierProducts;
//		this.productBundleDetails = productBundleDetails;
//		this.inventoryProducts = inventoryProducts;
//		this.projectActivityManagements = projectActivityManagements;
//		this.salesOrderProductDetails = salesOrderProductDetails;
//		this.projectTasks = projectTasks;
//		this.priceLists = priceLists;
//		this.inventoryActualstockSerializedProducts = inventoryActualstockSerializedProducts;
//		this.quoteProductDetails = quoteProductDetails;
//		this.inventoryIssues = inventoryIssues;
//		this.salesOrderSpecResponses = salesOrderSpecResponses;
//		this.inventoryActualStocks = inventoryActualStocks;
//		this.contractProductDetails = contractProductDetails;
//		this.assetMovements = assetMovements;
//		this.salesOrderProductDetails_1 = salesOrderProductDetails_1;
//	}

	@Id
	@Column(name = "ProductID", unique = true, nullable = false)
	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductSubTypeID")
	public ProductSubType getProductSubType() {
		return this.productSubType;
	}

	public void setProductSubType(ProductSubType productSubType) {
		this.productSubType = productSubType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductCategoryID")
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductSubCategoryID")
	public ProductSubCategory getProductSubCategory() {
		return this.productSubCategory;
	}

	public void setProductSubCategory(ProductSubCategory productSubCategory) {
		this.productSubCategory = productSubCategory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductTypeID")
	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SupplierProductID")
	public SupplierProduct getSupplierProduct() {
		return this.supplierProduct;
	}

	public void setSupplierProduct(SupplierProduct supplierProduct) {
		this.supplierProduct = supplierProduct;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "ProductDiscountID")
//	public ProductDiscount getProductDiscount() {
//		return this.productDiscount;
//	}
//
//	public void setProductDiscount(ProductDiscount productDiscount) {
//		this.productDiscount = productDiscount;
//	}

	@Column(name = "ProductName")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "ProductDescription")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	@Column(name = "ProductNumber")
	public String getProductNumber() {
		return this.productNumber;
	}

	public void setProductNumber(String productNumber) {
		this.productNumber = productNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PurchasedAt", length = 23)
	public Date getPurchasedAt() {
		return this.purchasedAt;
	}

	public void setPurchasedAt(Date purchasedAt) {
		this.purchasedAt = purchasedAt;
	}

	@Column(name = "WholeSaleRate", scale = 4)
	public BigDecimal getWholeSaleRate() {
		return this.wholeSaleRate;
	}

	public void setWholeSaleRate(BigDecimal wholeSaleRate) {
		this.wholeSaleRate = wholeSaleRate;
	}

	@Column(name = "RetailRate", scale = 4)
	public BigDecimal getRetailRate() {
		return this.retailRate;
	}

	public void setRetailRate(BigDecimal retailRate) {
		this.retailRate = retailRate;
	}

	@Column(name = "ProductUOM")
	public String getProductUom() {
		return this.productUom;
	}

	public void setProductUom(String productUom) {
		this.productUom = productUom;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getInventoryBookings() {
//		return this.inventoryBookings;
//	}
//
//	public void setInventoryBookings(Set inventoryBookings) {
//		this.inventoryBookings = inventoryBookings;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getOpportunityProductDetails() {
//		return this.opportunityProductDetails;
//	}
//
//	public void setOpportunityProductDetails(Set opportunityProductDetails) {
//		this.opportunityProductDetails = opportunityProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getPriceLevels() {
//		return this.priceLevels;
//	}
//
//	public void setPriceLevels(Set priceLevels) {
//		this.priceLevels = priceLevels;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getSupplierProducts() {
//		return this.supplierProducts;
//	}
//
//	public void setSupplierProducts(Set supplierProducts) {
//		this.supplierProducts = supplierProducts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getProductBundleDetails() {
//		return this.productBundleDetails;
//	}
//
//	public void setProductBundleDetails(Set productBundleDetails) {
//		this.productBundleDetails = productBundleDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getInventoryProducts() {
//		return this.inventoryProducts;
//	}
//
//	public void setInventoryProducts(Set inventoryProducts) {
//		this.inventoryProducts = inventoryProducts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getProjectActivityManagements() {
//		return this.projectActivityManagements;
//	}
//
//	public void setProjectActivityManagements(Set projectActivityManagements) {
//		this.projectActivityManagements = projectActivityManagements;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getSalesOrderProductDetails() {
//		return this.salesOrderProductDetails;
//	}
//
//	public void setSalesOrderProductDetails(Set salesOrderProductDetails) {
//		this.salesOrderProductDetails = salesOrderProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getProjectTasks() {
//		return this.projectTasks;
//	}
//
//	public void setProjectTasks(Set projectTasks) {
//		this.projectTasks = projectTasks;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getPriceLists() {
//		return this.priceLists;
//	}
//
//	public void setPriceLists(Set priceLists) {
//		this.priceLists = priceLists;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getInventoryActualstockSerializedProducts() {
//		return this.inventoryActualstockSerializedProducts;
//	}
//
//	public void setInventoryActualstockSerializedProducts(
//			Set inventoryActualstockSerializedProducts) {
//		this.inventoryActualstockSerializedProducts = inventoryActualstockSerializedProducts;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getQuoteProductDetails() {
//		return this.quoteProductDetails;
//	}
//
//	public void setQuoteProductDetails(Set quoteProductDetails) {
//		this.quoteProductDetails = quoteProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getInventoryIssues() {
//		return this.inventoryIssues;
//	}
//
//	public void setInventoryIssues(Set inventoryIssues) {
//		this.inventoryIssues = inventoryIssues;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getSalesOrderSpecResponses() {
//		return this.salesOrderSpecResponses;
//	}
//
//	public void setSalesOrderSpecResponses(Set salesOrderSpecResponses) {
//		this.salesOrderSpecResponses = salesOrderSpecResponses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getInventoryActualStocks() {
//		return this.inventoryActualStocks;
//	}
//
//	public void setInventoryActualStocks(Set inventoryActualStocks) {
//		this.inventoryActualStocks = inventoryActualStocks;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getContractProductDetails() {
//		return this.contractProductDetails;
//	}
//
//	public void setContractProductDetails(Set contractProductDetails) {
//		this.contractProductDetails = contractProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getAssetMovements() {
//		return this.assetMovements;
//	}
//
//	public void setAssetMovements(Set assetMovements) {
//		this.assetMovements = assetMovements;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
//	public Set getSalesOrderProductDetails_1() {
//		return this.salesOrderProductDetails_1;
//	}
//
//	public void setSalesOrderProductDetails_1(Set salesOrderProductDetails_1) {
//		this.salesOrderProductDetails_1 = salesOrderProductDetails_1;
//	}

}
