package com.seismic.crm.model;

// Generated Oct 8, 2013 8:42:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * ProductSubType generated by hbm2java
 */
@Entity
@Table(name = "ProductSubType", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class ProductSubType implements java.io.Serializable {

	private long productSubTypeId;
	private ProductType productType;
	private String productSubType;
	private String productSubTypeDesc;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
//	private Set salesOrderProductDetails = new HashSet(0);
	private Set products = new HashSet(0);

	public ProductSubType() {
	}

	public ProductSubType(long productSubTypeId, ProductType productType) {
		this.productSubTypeId = productSubTypeId;
		this.productType = productType;
	}

	public ProductSubType(long productSubTypeId, ProductType productType,
			String productSubType, String productSubTypeDesc, Boolean isActive,
			String createdBy, Date createdAt, String modifiedBy,
			Date modifiedAt, String remarks, /*Set salesOrderProductDetails,*/
			Set products) {
		this.productSubTypeId = productSubTypeId;
		this.productType = productType;
		this.productSubType = productSubType;
		this.productSubTypeDesc = productSubTypeDesc;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
//		this.salesOrderProductDetails = salesOrderProductDetails;
		this.products = products;
	}

	@Id
	@Column(name = "ProductSubTypeID", unique = true, nullable = false)
	public long getProductSubTypeId() {
		return this.productSubTypeId;
	}

	public void setProductSubTypeId(long productSubTypeId) {
		this.productSubTypeId = productSubTypeId;
	}
	@JsonManagedReference
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductTypeID", nullable = false)
	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	@Column(name = "ProductSubType")
	public String getProductSubType() {
		return this.productSubType;
	}

	public void setProductSubType(String productSubType) {
		this.productSubType = productSubType;
	}

	@Column(name = "ProductSubTypeDesc")
	public String getProductSubTypeDesc() {
		return this.productSubTypeDesc;
	}

	public void setProductSubTypeDesc(String productSubTypeDesc) {
		this.productSubTypeDesc = productSubTypeDesc;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSubType")
	public Set getSalesOrderProductDetails() {
		return this.salesOrderProductDetails;
	}

	public void setSalesOrderProductDetails(Set salesOrderProductDetails) {
		this.salesOrderProductDetails = salesOrderProductDetails;
	}*/
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY/*, mappedBy = "productSubType"*/)
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}


}
