package com.seismic.crm.model;

// Generated Nov 14, 2013 4:21:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductSubCategory generated by hbm2java
 */
@Entity
@Table(name = "ProductSubCategory", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class ProductSubCategory implements java.io.Serializable {

	private long productSubCategoryId;
	private ProductCategory productCategory;
	private String productSubCategoryName;
	private String productSubCategoryDesc;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
//	private Set salesOrderProductDetails = new HashSet(0);
//	private Set productTypes = new HashSet(0);
//	private Set products = new HashSet(0);

	public ProductSubCategory() {
	}

	public ProductSubCategory(long productSubCategoryId) {
		this.productSubCategoryId = productSubCategoryId;
	}

//	public ProductSubCategory(long productSubCategoryId,
//			ProductCategory productCategory, String productSubCategoryName,
//			String productSubCategoryDesc, Boolean isActive, String createdBy,
//			Date createdAt, String modifiedBy, Date modifiedAt, String remarks,
//			Set salesOrderProductDetails, Set productTypes, Set products) {
//		this.productSubCategoryId = productSubCategoryId;
//		this.productCategory = productCategory;
//		this.productSubCategoryName = productSubCategoryName;
//		this.productSubCategoryDesc = productSubCategoryDesc;
//		this.isActive = isActive;
//		this.createdBy = createdBy;
//		this.createdAt = createdAt;
//		this.modifiedBy = modifiedBy;
//		this.modifiedAt = modifiedAt;
//		this.remarks = remarks;
//		this.salesOrderProductDetails = salesOrderProductDetails;
//		this.productTypes = productTypes;
//		this.products = products;
//	}

	@Id
	@Column(name = "ProductSubCategoryID", unique = true, nullable = false)
	public long getProductSubCategoryId() {
		return this.productSubCategoryId;
	}

	public void setProductSubCategoryId(long productSubCategoryId) {
		this.productSubCategoryId = productSubCategoryId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ProductCategoryID")
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "ProductSubCategoryName")
	public String getProductSubCategoryName() {
		return this.productSubCategoryName;
	}

	public void setProductSubCategoryName(String productSubCategoryName) {
		this.productSubCategoryName = productSubCategoryName;
	}

	@Column(name = "ProductSubCategoryDesc")
	public String getProductSubCategoryDesc() {
		return this.productSubCategoryDesc;
	}

	public void setProductSubCategoryDesc(String productSubCategoryDesc) {
		this.productSubCategoryDesc = productSubCategoryDesc;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productSubCategory")
//	public Set getSalesOrderProductDetails() {
//		return this.salesOrderProductDetails;
//	}
//
//	public void setSalesOrderProductDetails(Set salesOrderProductDetails) {
//		this.salesOrderProductDetails = salesOrderProductDetails;
//	}
//
//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productSubCategory")
//	public Set getProductTypes() {
//		return this.productTypes;
//	}
//
//	public void setProductTypes(Set productTypes) {
//		this.productTypes = productTypes;
//	}
//
//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "productSubCategory")
//	public Set getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set products) {
//		this.products = products;
//	}

}
