package com.seismic.crm.model;

// Generated Sep 10, 2013 12:27:44 PM by Hibernate Tools 4.0.0

import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "ProductCategory", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class ProductCategory implements java.io.Serializable {

	private Long productCategoryId;
	private String productCategory;
	private String productCatergoryDesc;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
	// private Set productTypes = new HashSet(0);
	private Set salesOrderProductDetails = new HashSet(0);
	private Set products = new HashSet(0);
	private Set productSubCategory = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(Long productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public ProductCategory(long productCategoryId, String productCategory,
			String productCatergoryDesc, Boolean isActive, String createdBy,
			Date createdAt, String modifiedBy, Date modifiedAt, String remarks,
			/*Set productTypes, */Set salesOrderProductDetails,/* Set products,*/ Set productSubCategory) {
		this.productCategoryId = productCategoryId;
		this.productCategory = productCategory;
		this.productCatergoryDesc = productCatergoryDesc;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
		// this.productTypes = productTypes;
		this.salesOrderProductDetails = salesOrderProductDetails;
		// this.products = products;
		this.productSubCategory=productSubCategory;
	}

	@Id
	@Column(name = "ProductCategoryID", unique = true, nullable = false)
	public Long getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(Long productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	@Column(name = "ProductCategory")
	public String getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(String productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "ProductCatergoryDesc")
	public String getProductCatergoryDesc() {
		return this.productCatergoryDesc;
	}

	public void setProductCatergoryDesc(String productCatergoryDesc) {
		this.productCatergoryDesc = productCatergoryDesc;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productCategory")
//	public Set getProductTypes() {
//		return this.productTypes;
//	}
//
//	public void setProductTypes(Set productTypes) {
//		this.productTypes = productTypes;
//	}
//

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY/*, mappedBy = "productCategory"*/)
	public Set<SalesOrderProductDetail> getSalesOrderProductDetails() {
		return this.salesOrderProductDetails;
	}

	public void setSalesOrderProductDetails(Set salesOrderProductDetails) {
		this.salesOrderProductDetails = salesOrderProductDetails;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY/*, mappedBy = "productCategory"*/)
	public Set<Product> getProducts() {
		return products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}
	
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY/*, mappedBy = "productCategory"*/)	
	public Set <ProductSubCategory> getProductSubCategory() {
		return productSubCategory;
	}

	public void setProductSubCategory(Set<ProductSubCategory> productSubCategory) {
		this.productSubCategory = productSubCategory;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((productCategoryId == null) ? 0 : productCategoryId
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;	
		ProductCategory other = (ProductCategory) obj;
		if (productCategoryId == null) {
			if (other.productCategoryId != null)
				return false;
		} else if (!productCategoryId.equals(other.productCategoryId))
			return false;
		return true;
	}

}
