package com.seismic.crm.model;

// Generated Nov 13, 2013 3:55:26 PM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class Project implements java.io.Serializable {

	private long projectId;
//	private Contract contract;
	private SalesOrder salesOrder;
	private String accountId;
	private String projectAccountName;
	private String projectNumber;
	private String projectDesc;
	private String projectContractName;
	private Date projectStartDate;
	private Date projectEndDate;
	private Date projectActualStartDate;
	private Date projectActualEndDate;
	private String projectAssignedTo;
	private String projectStatus;
	private String projectType;
	private String projectBudget;
	private Integer projectEstimatedEffort;
	private Serializable projectActualCost;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
//	private Set projectMileStones = new HashSet(0);
//	private Set projectActivityManagements = new HashSet(0);
//	private Set salesOrders = new HashSet(0);

	public Project() {
	}

	public Project(long projectId) {
		this.projectId = projectId;
	}

//	public Project(long projectId, Contract contract, SalesOrder salesOrder,
//			String accountId, String projectAccountName, String projectNumber,
//			String projectDesc, String projectContractName,
//			Date projectStartDate, Date projectEndDate,
//			Date projectActualStartDate, Date projectActualEndDate,
//			String projectAssignedTo, String projectStatus, String projectType,
//			String projectBudget, Integer projectEstimatedEffort,
//			Serializable projectActualCost, Boolean isActive, String createdBy,
//			Date createdAt, String modifiedBy, Date modifiedAt, String remarks,
//			Set projectMileStones, Set projectActivityManagements,
//			Set salesOrders) {
//		this.projectId = projectId;
////		this.contract = contract;
//		this.salesOrder = salesOrder;
//		this.accountId = accountId;
//		this.projectAccountName = projectAccountName;
//		this.projectNumber = projectNumber;
//		this.projectDesc = projectDesc;
//		this.projectContractName = projectContractName;
//		this.projectStartDate = projectStartDate;
//		this.projectEndDate = projectEndDate;
//		this.projectActualStartDate = projectActualStartDate;
//		this.projectActualEndDate = projectActualEndDate;
//		this.projectAssignedTo = projectAssignedTo;
//		this.projectStatus = projectStatus;
//		this.projectType = projectType;
//		this.projectBudget = projectBudget;
//		this.projectEstimatedEffort = projectEstimatedEffort;
//		this.projectActualCost = projectActualCost;
//		this.isActive = isActive;
//		this.createdBy = createdBy;
//		this.createdAt = createdAt;
//		this.modifiedBy = modifiedBy;
//		this.modifiedAt = modifiedAt;
//		this.remarks = remarks;
////		this.projectMileStones = projectMileStones;
////		this.projectActivityManagements = projectActivityManagements;
////		this.salesOrders = salesOrders;
//	}

	@Id
	@Column(name = "ProjectID", unique = true, nullable = false)
	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "ContractID")
//	public Contract getContract() {
//		return this.contract;
//	}
//
//	public void setContract(Contract contract) {
//		this.contract = contract;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SalesOrderID")
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@Column(name = "AccountID")
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "ProjectAccountName")
	public String getProjectAccountName() {
		return this.projectAccountName;
	}

	public void setProjectAccountName(String projectAccountName) {
		this.projectAccountName = projectAccountName;
	}

	@Column(name = "ProjectNumber")
	public String getProjectNumber() {
		return this.projectNumber;
	}

	public void setProjectNumber(String projectNumber) {
		this.projectNumber = projectNumber;
	}

	@Column(name = "ProjectDesc")
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "ProjectContractName")
	public String getProjectContractName() {
		return this.projectContractName;
	}

	public void setProjectContractName(String projectContractName) {
		this.projectContractName = projectContractName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ProjectStartDate", length = 23)
	public Date getProjectStartDate() {
		return this.projectStartDate;
	}

	public void setProjectStartDate(Date projectStartDate) {
		this.projectStartDate = projectStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ProjectEndDate", length = 23)
	public Date getProjectEndDate() {
		return this.projectEndDate;
	}

	public void setProjectEndDate(Date projectEndDate) {
		this.projectEndDate = projectEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ProjectActualStartDate", length = 23)
	public Date getProjectActualStartDate() {
		return this.projectActualStartDate;
	}

	public void setProjectActualStartDate(Date projectActualStartDate) {
		this.projectActualStartDate = projectActualStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ProjectActualEndDate", length = 23)
	public Date getProjectActualEndDate() {
		return this.projectActualEndDate;
	}

	public void setProjectActualEndDate(Date projectActualEndDate) {
		this.projectActualEndDate = projectActualEndDate;
	}

	@Column(name = "ProjectAssignedTo")
	public String getProjectAssignedTo() {
		return this.projectAssignedTo;
	}

	public void setProjectAssignedTo(String projectAssignedTo) {
		this.projectAssignedTo = projectAssignedTo;
	}

	@Column(name = "ProjectStatus")
	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	@Column(name = "ProjectType")
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@Column(name = "ProjectBudget")
	public String getProjectBudget() {
		return this.projectBudget;
	}

	public void setProjectBudget(String projectBudget) {
		this.projectBudget = projectBudget;
	}

	@Column(name = "ProjectEstimatedEffort")
	public Integer getProjectEstimatedEffort() {
		return this.projectEstimatedEffort;
	}

	public void setProjectEstimatedEffort(Integer projectEstimatedEffort) {
		this.projectEstimatedEffort = projectEstimatedEffort;
	}

	@Column(name = "ProjectActualCost")
	public Serializable getProjectActualCost() {
		return this.projectActualCost;
	}

	public void setProjectActualCost(Serializable projectActualCost) {
		this.projectActualCost = projectActualCost;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
//	public Set getProjectMileStones() {
//		return this.projectMileStones;
//	}
//
//	public void setProjectMileStones(Set projectMileStones) {
//		this.projectMileStones = projectMileStones;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
//	public Set getProjectActivityManagements() {
//		return this.projectActivityManagements;
//	}
//
//	public void setProjectActivityManagements(Set projectActivityManagements) {
//		this.projectActivityManagements = projectActivityManagements;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
//	public Set getSalesOrders() {
//		return this.salesOrders;
//	}
//
//	public void setSalesOrders(Set salesOrders) {
//		this.salesOrders = salesOrders;
//	}

}
