package com.seismic.crm.model;

// Generated Jan 6, 2014 9:20:23 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * SfActivityResponse generated by hbm2java
 */
@Entity
@Table(name = "SfSpecActivityResponse", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class SfSpecActivityResponse implements java.io.Serializable {

	private long activityResponseId;
	private SoSpecTaskResponse soSpecTaskResponse;
	private SfSpecActivity sfSpecActivity;
	private Date activityStartDate;
	private Date activityEndDate;
	private String assignedTo;
	private Boolean selectedFlag = false;

	public SfSpecActivityResponse() {
	}

	public SfSpecActivityResponse(long activityResponseId) {
		this.activityResponseId = activityResponseId;
	}

	public SfSpecActivityResponse(long activityResponseId,
			SoSpecTaskResponse soSpecTaskResponse,
			SfSpecActivity sfSpecActivity, Date activityStartDate,
			Date activityEndDate, String assignedTo, Boolean selectedFlag) {
		this.activityResponseId = activityResponseId;
		this.soSpecTaskResponse = soSpecTaskResponse;
		this.sfSpecActivity = sfSpecActivity;
		this.activityStartDate = activityStartDate;
		this.activityEndDate = activityEndDate;
		this.assignedTo = assignedTo;
		this.selectedFlag = selectedFlag;
	}

	@Id
	@GeneratedValue
	@Column(name = "ActivityResponseID", unique = true, nullable = false)
	public long getActivityResponseId() {
		return this.activityResponseId;
	}

	public void setActivityResponseId(long activityResponseId) {
		this.activityResponseId = activityResponseId;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TaskResponseID")
	public SoSpecTaskResponse getSoSpecTaskResponse() {
		return this.soSpecTaskResponse;
	}

	public void setSoSpecTaskResponse(SoSpecTaskResponse soSpecTaskResponse) {
		this.soSpecTaskResponse = soSpecTaskResponse;
	}

//	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ActivityID")
	public SfSpecActivity getSfSpecActivity() {
		return this.sfSpecActivity;
	}

	public void setSfSpecActivity(SfSpecActivity sfSpecActivity) {
		this.sfSpecActivity = sfSpecActivity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ActivityStartDate", length = 10)
	public Date getActivityStartDate() {
		return this.activityStartDate;
	}

	public void setActivityStartDate(Date activityStartDate) {
		this.activityStartDate = activityStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ActivityEndDate", length = 10)
	public Date getActivityEndDate() {
		return this.activityEndDate;
	}

	public void setActivityEndDate(Date activityEndDate) {
		this.activityEndDate = activityEndDate;
	}

	@Column(name = "AssignedTo")
	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "selectedFlag")
	public Boolean getSelectedFlag() {
		return this.selectedFlag;
	}

	public void setSelectedFlag(Boolean selectedFlag) {
		this.selectedFlag = selectedFlag;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ (int) (activityResponseId ^ (activityResponseId >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof SfSpecActivityResponse))
			return false;
		SfSpecActivityResponse other = (SfSpecActivityResponse) obj;
		if (activityResponseId != other.activityResponseId)
			return false;
		return true;
	}

}
