package com.seismic.crm.model;

// Generated 13 Jan, 2014 4:42:11 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeneralAlerts generated by hbm2java
 */
@Entity
@Table(name = "GeneralAlerts", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class GeneralAlerts implements java.io.Serializable {

	private String generalAlertsId;
	private String moduleId;
	private String moduleName;
	private String generalAlertsFrom;
	private String generalAlertsTo;
	private String generalAlertsCc;
	private String generalAlertsBcc;
	private String generalAlertsSubject;
	private String generalAlertsBody;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;

	public GeneralAlerts() {
	}

	public GeneralAlerts(String generalAlertsId, String moduleId,
			String generalAlertsFrom, String generalAlertsTo) {
		this.generalAlertsId = generalAlertsId;
		this.moduleId = moduleId;
		this.generalAlertsFrom = generalAlertsFrom;
		this.generalAlertsTo = generalAlertsTo;
	}

	public GeneralAlerts(String generalAlertsId, String moduleId,
			String moduleName, String generalAlertsFrom,
			String generalAlertsTo, String generalAlertsCc,
			String generalAlertsBcc, String generalAlertsSubject,
			String generalAlertsBody, String createdBy, Date createdAt,
			String modifiedBy, Date modifiedAt) {
		this.generalAlertsId = generalAlertsId;
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.generalAlertsFrom = generalAlertsFrom;
		this.generalAlertsTo = generalAlertsTo;
		this.generalAlertsCc = generalAlertsCc;
		this.generalAlertsBcc = generalAlertsBcc;
		this.generalAlertsSubject = generalAlertsSubject;
		this.generalAlertsBody = generalAlertsBody;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
	}

	@Id
	@Column(name = "GeneralAlertsId", unique = true, nullable = false)
	public String getGeneralAlertsId() {
		return this.generalAlertsId;
	}

	public void setGeneralAlertsId(String generalAlertsId) {
		this.generalAlertsId = generalAlertsId;
	}

	@Column(name = "ModuleId", nullable = false)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "ModuleName")
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "GeneralAlertsFrom", nullable = false)
	public String getGeneralAlertsFrom() {
		return this.generalAlertsFrom;
	}

	public void setGeneralAlertsFrom(String generalAlertsFrom) {
		this.generalAlertsFrom = generalAlertsFrom;
	}

	@Column(name = "GeneralAlertsTo", nullable = false)
	public String getGeneralAlertsTo() {
		return this.generalAlertsTo;
	}

	public void setGeneralAlertsTo(String generalAlertsTo) {
		this.generalAlertsTo = generalAlertsTo;
	}

	@Column(name = "GeneralAlertsCc")
	public String getGeneralAlertsCc() {
		return this.generalAlertsCc;
	}

	public void setGeneralAlertsCc(String generalAlertsCc) {
		this.generalAlertsCc = generalAlertsCc;
	}

	@Column(name = "GeneralAlertsBcc")
	public String getGeneralAlertsBcc() {
		return this.generalAlertsBcc;
	}

	public void setGeneralAlertsBcc(String generalAlertsBcc) {
		this.generalAlertsBcc = generalAlertsBcc;
	}

	@Column(name = "GeneralAlertsSubject")
	public String getGeneralAlertsSubject() {
		return this.generalAlertsSubject;
	}

	public void setGeneralAlertsSubject(String generalAlertsSubject) {
		this.generalAlertsSubject = generalAlertsSubject;
	}

	@Column(name = "GeneralAlertsBody")
	public String getGeneralAlertsBody() {
		return this.generalAlertsBody;
	}

	public void setGeneralAlertsBody(String generalAlertsBody) {
		this.generalAlertsBody = generalAlertsBody;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

}
