package com.seismic.crm.model;

// Generated Sep 24, 2013 7:40:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierProduct generated by hbm2java
 */
@Entity
@Table(name = "SupplierProduct", schema = "dbo", catalog = "SEISMIC_CRM_DEV")
public class SupplierProduct implements java.io.Serializable {

	private long supplierProductId;
	private Product product;
	private Contact contact;
	private String supplierProductName;
	private String supplierProductCode;
	private String supplierProductNumber;
	private String supplierProductUom;
	private Double supplierProductRetailPrice;
	private Double supplierProductWholeSalePrice;
	private Double supplierDiscount;
	private String supplierProductDescription;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private Date modifiedAt;
	private String remarks;
//	private Set salesOrderProductDetails = new HashSet(0);

	public SupplierProduct() {
	}

	public SupplierProduct(long supplierProductId) {
		this.supplierProductId = supplierProductId;
	}

	@Id
	@Column(name = "SupplierProductID", unique = true, nullable = false)
	public long getSupplierProductId() {
		return this.supplierProductId;
	}

	public void setSupplierProductId(long supplierProductId) {
		this.supplierProductId = supplierProductId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OwnProductID")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SupplierID")
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "SupplierProductName")
	public String getSupplierProductName() {
		return this.supplierProductName;
	}

	public void setSupplierProductName(String supplierProductName) {
		this.supplierProductName = supplierProductName;
	}

	@Column(name = "SupplierProductCode")
	public String getSupplierProductCode() {
		return this.supplierProductCode;
	}

	public void setSupplierProductCode(String supplierProductCode) {
		this.supplierProductCode = supplierProductCode;
	}

	@Column(name = "SupplierProductNumber")
	public String getSupplierProductNumber() {
		return this.supplierProductNumber;
	}

	public void setSupplierProductNumber(String supplierProductNumber) {
		this.supplierProductNumber = supplierProductNumber;
	}

	@Column(name = "SupplierProductUOM")
	public String getSupplierProductUom() {
		return this.supplierProductUom;
	}

	public void setSupplierProductUom(String supplierProductUom) {
		this.supplierProductUom = supplierProductUom;
	}

	@Column(name = "SupplierProductRetailPrice", scale = 4)
	public Double getSupplierProductRetailPrice() {
		return this.supplierProductRetailPrice;
	}

	public void setSupplierProductRetailPrice(
			Double supplierProductRetailPrice) {
		this.supplierProductRetailPrice = supplierProductRetailPrice;
	}

	@Column(name = "SupplierProductWholeSalePrice", scale = 4)
	public Double getSupplierProductWholeSalePrice() {
		return this.supplierProductWholeSalePrice;
	}

	public void setSupplierProductWholeSalePrice(
			Double supplierProductWholeSalePrice) {
		this.supplierProductWholeSalePrice = supplierProductWholeSalePrice;
	}

	@Column(name = "SupplierDiscount")
	public Double getSupplierDiscount() {
		return this.supplierDiscount;
	}

	public void setSupplierDiscount(Double supplierDiscount) {
		this.supplierDiscount = supplierDiscount;
	}

	@Column(name = "SupplierProductDescription")
	public String getSupplierProductDescription() {
		return this.supplierProductDescription;
	}

	public void setSupplierProductDescription(String supplierProductDescription) {
		this.supplierProductDescription = supplierProductDescription;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "CreatedBy")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifiedAt", length = 23)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	@Column(name = "Remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierProduct")
//	public Set getSalesOrderProductDetails() {
//		return this.salesOrderProductDetails;
//	}
//
//	public void setSalesOrderProductDetails(Set salesOrderProductDetails) {
//		this.salesOrderProductDetails = salesOrderProductDetails;
//	}

}
