package com.seismic.crm.model;

// Generated Nov 8, 2013 12:48:36 PM by Hibernate Tools 4.0.0

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalesOrder generated by hbm2java
 */
@Entity
@Table(name = "CheckListDocument", schema = "dbo", catalog = "Seismic_Crm_Dev")
public class CheckList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long documentId;
	private String documentName;
	private String documentSeq;
	private Boolean isActive;
	private String createdBy;
	private Date createdAt;
	private String modifiedBy;
	private String modifiedAt;
	private String remarks;                 
	
	public CheckList() {  
	}

	public CheckList(long documentId) {
		this.documentId = documentId;
	}
	
	public CheckList(long documentId, String documentName, String documentSeq,
			Boolean isActive, String createdBy, Date createdAt,
			String modifiedBy, String modifiedAt, String remarks) {
		super();
		this.documentId = documentId;
		this.documentName = documentName;
		this.documentSeq = documentSeq;
		this.isActive = isActive;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.modifiedBy = modifiedBy;
		this.modifiedAt = modifiedAt;
		this.remarks = remarks;
	}
	
	@Id
	@GeneratedValue	
	@Column(name = "CheckListDocumentID", unique = true, nullable = false)
	public long getDocumentId() {
		return documentId;             
	}
	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}
	
	@Column(name = "CheckListDocumentName")
	public String getDocumentName() {
		return documentName;
	}
	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}
	
	@Column(name = "CheckListDocumentSeq")
	public String getDocumentSeq() {
		return documentSeq;
	}
	public void setDocumentSeq(String documentSeq) {
		this.documentSeq = documentSeq;
	}
	
	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return isActive;
	}
	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	
	@Column(name = "Createdby")
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name = "CreatedAt")
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	
	@Column(name = "ModifiedBy")
	public String getModifiedBy() {
		return modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	
	@Column(name = "ModifiedAt")
	public String getModifiedAt() {
		return modifiedAt;
	}
	public void setModifiedAt(String modifiedAt) {
		this.modifiedAt = modifiedAt;
	}
	
	@Column(name = "Remarks")
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
		
		
}
